source "https://rubygems.org"

# Mandatory minimal gems for Scarpe-Wasm and for packaging
gem "scarpe-components", github: "scarpe-team/scarpe",branch:"main", glob: "scarpe-components/*.gemspec"
gem "lacci", github: "scarpe-team/scarpe", branch:"main",glob: "lacci/*.gemspec"

gem "scarpe-wasm", path: ".."

# Technically we could remove this with some work - don't need wasify in ruby.wasm package
gem "wasify", github: "AlawysDelta/wasify"

# What other gems should we assume we need?
