source "https://rubygems.org"

# These gems can be installed at a path or git branch if you're doing development.
# Remember that lacci should also be specified if you're modifying it.

gem "scarpe-components", github: "scarpe-team/scarpe", glob: "scarpe-components/*.gemspec"
#gem "scarpe-components", path: "../../../scarpe/scarpe-components"

gem "lacci", github: "scarpe-team/scarpe", glob: "lacci/*.gemspec"

gem "scarpe-wasm", path: "../.."

gem "wasify", github: "AlawysDelta/wasify", branch: "ruby_3_3_and_later_ruby_wasm" #path: "../../../wasify"

gem "webrick" # to use "ruby -run -e httpd"
